modLoader = "javafml"
loaderVersion = "[2,)"
#issueTrackerURL = ""
license = "GNU LGPL 3.0"

[[mods]]
modId = "cookiecrafter"
version = "${version}"
displayName = "Cookie Crafter"
authors = "ThePoultryMan"
description = '''
Cookie Clicker but in Minecraft
'''
#logoFile = ""

[[dependencies.cookiecrafter]]
modId = "neoforge"
type = "required"
versionRange = "[21,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.cookiecrafter]]
modId = "minecraft"
type = "required"
versionRange = "[1.21.1,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.cookiecrafter]]
modId = "architectury"
type = "required"
versionRange = "[13.0.6,)"
ordering = "AFTER"
side = "BOTH"

[[mixins]]
config = "cookiecrafter.mixins.json"
